strict_mode = true

blacklist = [".*build.*", "^/usr*"]

sort_order = ["tmux", "config", "zoxide"]

[default_session]
startup_command = "~/.config/sesh/scripts/layout_dispatcher {}"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Textura pick worktree"
path = "~/Projects/cpp/Textura"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "Editor pick worktree"
path = "~/Projects/cpp/Editor"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "IronCount pick worktree"
path = "~/Projects/rust/IronCount"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "optica pick worktree"
path = "~/Projects/cpp/optica"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "shape_reward pick worktree"
path = "~/code/work/shape_reward/"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "archive pick worktree"
path = "~/Projects/lua/archive"
startup_command = "sesh connect (find . -maxdepth 1 -type d | gum filter --limit 1 --fuzzy --no-sort --placeholder 'Pick a worktree' --prompt='🌲') && exit"

[[session]]
name = "Beancount"
path = "~/Documents/finance"
startup_command = "~/.config/sesh/scripts/beancount_template"

[[session]]
name = "Nvim Config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "Sesh Config"
path = "~/.config/sesh"
startup_command = "nvim"

[[session]]
name = "Hyprland Config"
path = "~/.config/hypr"
startup_command = "nvim"

[[session]]
name = "Niri Config"
path = "~/.config/niri"
startup_command = "nvim"

[[session]]
name = "Tmux Config"
path = "~/.config/tmux"
startup_command = "nvim"
