unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -g prefix M-e
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key "K" display-popup -E -w 40% "sesh connect \"$(
 sesh list -i | gum filter --no-strip-ansi --limit 1 --no-sort --fuzzy --placeholder 'Pick a sesh' --height 50 --prompt='⚡'
)\""


set-option -sg escape-time 10
set-option -g focus-events on
set -g pane-border-lines double

set -g default-terminal "tmux-256color"
set -as terminal-features ",*256col*:RGB"
set-option -g status-position top
set -g base-index 1
set -g renumber-windows on

set -g @kanagawa-override-theme 'kanagawa'
set -g @kanagawa-plugins "git time"
set -g @kanagawa-show-powerline true
set -g @kanagawa-show-edge-icons true
set -g @kanagawa-ignore-window-colors true
set -g @continuum-save-interval '15'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

run '~/.config/tmux/plugins/tpm/tpm'
