unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-a
set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key "K" display-popup -E -w 40% "sesh connect \"$(
 sesh list -i | gum filter --no-strip-ansi --limit 1 --no-sort --fuzzy --placeholder 'Pick a sesh' --height 50 --prompt='⚡'
)\""


set-option -sg escape-time 10
set-option -g focus-events on

set-option -g  default-terminal "foot"
set-option -ga terminal-overrides ",foot:Tc"
set-option -g status-position top
set -g base-index 1
set -g renumber-windows on

set -g @tokyo-night-tmux_theme storm

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

run '~/.tmux/plugins/tpm/tpm'
